services:
  web:
    build: .
    command: bundle exec puma -C config/puma.rb
    volumes:
      - .:/kumazaki-insta-app
    ports:
      - "3000:3000"
    depends_on:
      - db
      - redis
    env_file:
      - .env.development

  sidekiq:
    build: .
    command: bundle exec sidekiq -C config/sidekiq.yml
    volumes:
      - .:/kumazaki-insta-app
    depends_on:
      - db
      - redis

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"

  webpacker:
    build: .
    command: ./bin/webpack-dev-server
    volumes:
      - .:/kumazaki-insta-app
    ports:
      - "3035:3035"
    depends_on:
      - db
      - redis


  db:
    image: postgres:14.9
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: myapp_development

volumes:
  postgres_data: