name: Deploy to Heroku

on:
  push:
    branches:
      - master

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Log in to Heroku Container Registry
        run: echo ${{ secrets.HEROKU_API_KEY }} | docker login --username=_ --password-stdin registry.heroku.com

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: registry.heroku.com/kumazaki-insta-app/web
          platforms: linux/amd64

      - name: Release Docker image to Heroku
        run: heroku container:release web -a kumazaki-insta-app
        env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
